### ISSUE TITLE
ArgumentError in join_dependency.rb on edge

### ISSUE THREAD

**Issue by dammer** [activerecord-hackery/polyamorous#18]
```ruby
irb(main):012:0> 
t1 = Theme.find(1)
irb(main):013:0> t1.place
t1.place_ids         t1.place_theme_ids   t1.place_themes      t1.places            
t1.place_ids=        t1.place_theme_ids=  t1.place_themes=     t1.places=           
irb(main):013:0> t1.places
ArgumentError: wrong number of arguments (2 for 1)
	from /=skipped=/.bundle/gems/gems/polyamorous-1.2.0/lib/polyamorous/activerecord_4.2_ruby_2/join_dependency.rb:56:in `join_constraints'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/relation/query_methods.rb:1010:in `build_join_query'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/relation/query_methods.rb:991:in `build_joins'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/relation/query_methods.rb:901:in `build_arel'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/relation/query_methods.rb:888:in `arel'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/relation/query_methods.rb:96:in `bound_attributes'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/statement_cache.rb:94:in `create'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/associations/collection_association.rb:447:in `block in get_records'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/reflection.rb:361:in `block in association_scope_cache'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/reflection.rb:360:in `synchronize'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/reflection.rb:360:in `association_scope_cache'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/reflection.rb:938:in `association_scope_cache'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/associations/collection_association.rb:446:in `get_records'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/associations/has_many_through_association.rb:194:in `find_target'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/associations/collection_association.rb:401:in `load_target'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/associations/collection_proxy.rb:45:in `load_target'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/associations/collection_proxy.rb:968:in `to_ary'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/activerecord/lib/active_record/relation.rb:676:in `inspect'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/railties/lib/rails/commands/console.rb:65:in `start'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/railties/lib/rails/commands/console_helper.rb:9:in `start'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/railties/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/railties/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /=skipped=/.bundle/gems/bundler/gems/rails-53d04697d5c9/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'irb(main):014:0> 
```
and when ransack removed from Gemfile:

```ruby
irb(main):008:0>t1 = Theme.find(1)
irb(main):009:0> t1.places
  Place Load (0.2ms)  SELECT "places".* FROM "places" INNER JOIN "place_themes" ON "places"."id" = "place_themes"."place_id" WHERE "place_themes"."theme_id" = ?  [["theme_id", 1]]
=> #<ActiveRecord::Associations::CollectionProxy []>
```

compatiblity broken in 
https://github.com/rails/rails/commit/3f46ef1ddab87482b730a3f53987e04308783d8b
added ActiveRecord::Relation#left_outer_joins
Example:
  User.left_outer_joins(:posts)
  => SELECT "users".* FROM "users" LEFT OUTER JOIN "posts" ON "posts"."user_id" = "users"."id"

**Comment by audionerd** [comment]
I had a similar problem on a Rails 5 app – I had to switch to `master`, which includes `activerecord_5.0_ruby_2/join_dependency.rb` instead of `activerecord_4.2_ruby_2/join_dependency.rb`. That seemed to fix my issue.

**Comment by dammer** [comment]
Great! it work to me  too) Мany thanks audionerd!

**Comment by jonatack** [comment]
Thanks @audionerd. Good to hear that master is working. I was waiting for any feedback on my changes for Rails 5 before pushing a new release, but a release is definitely overdue as Rails 5.0 beta should be out next week. Will get on it.

**Comment by audionerd** [comment]
I'll caveat that by saying I just added ransack to my Rails 5 project this week, so my use case so far is light. I'll keep in touch if I notice any issues as I advance with it.

**Comment by jonatack** [comment]
Great, thanks. 

I've been using Rails 5 with Ransack ever since Rails master was bumped to 5.0 and haven't had any problems apart from those I've fixed, but I use Ransack quite conservatively.

So always helpful to hear feedback.
