### ISSUE TITLE
wrong number of arguments Error when updating to Rails 5.2.1

### ISSUE THREAD

**Issue by yskkin** [activerecord-hackery/polyamorous#43]
I got this error. arity of JoinAssociation#initialize did changed between 5.2.0 and 5.2.1

```
ArgumentError - wrong number of arguments (given 3, expected 2):
  activerecord (5.2.1) lib/active_record/associations/join_dependency/join_association.rb:12:in `initialize'
  polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_association.rb:19:in `initialize'
  polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:28:in `new'
  polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:28:in `block in build'
  polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `each'
  polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `map'
  polyamorous (1.3.3) lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:8:in `build'
  activerecord (5.2.1) lib/active_record/associations/join_dependency.rb:72:in `initialize'
  activerecord (5.2.1) lib/active_record/relation/finder_methods.rb:376:in `new'
  activerecord (5.2.1) lib/active_record/relation/finder_methods.rb:376:in `construct_join_dependency'
  activerecord (5.2.1) lib/active_record/relation/finder_methods.rb:382:in `apply_join_dependency'
  activerecord (5.2.1) lib/active_record/relation.rb:544:in `block in exec_queries'
  activerecord (5.2.1) lib/active_record/relation.rb:578:in `skip_query_cache_if_necessary'
  activerecord (5.2.1) lib/active_record/relation.rb:541:in `exec_queries'
  activerecord (5.2.1) lib/active_record/relation.rb:414:in `load'
  activerecord (5.2.1) lib/active_record/relation.rb:200:in `records'
  bullet (5.7.5) lib/bullet/active_record52.rb:50:in `records'
  activerecord (5.2.1) lib/active_record/relation/delegation.rb:41:in `each'
  app/views/articles/index.html.slim:14:in `_app_views_articles_index_html_slim___1619308452723666076_70194417953960'
  actionview (5.2.1) lib/action_view/template.rb:159:in `block in render'
  activesupport (5.2.1) lib/active_support/notifications.rb:170:in `instrument'
  actionview (5.2.1) lib/action_view/template.rb:354:in `instrument_render_template'
  actionview (5.2.1) lib/action_view/template.rb:157:in `render'
   () usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/rack-mini-profiler-ab2d911d2c17/lib/mini_profiler/profiling_methods.rb:104:in `block in profile_method'
  actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (5.2.1) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
  activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
  activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
  actionview (5.2.1) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
  actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:16:in `render'
  actionview (5.2.1) lib/action_view/renderer/renderer.rb:44:in `render_template'
  actionview (5.2.1) lib/action_view/renderer/renderer.rb:25:in `render'
  actionview (5.2.1) lib/action_view/rendering.rb:103:in `_render_template'
  actionpack (5.2.1) lib/action_controller/metal/streaming.rb:219:in `_render_template'
  actionview (5.2.1) lib/action_view/rendering.rb:84:in `render_to_body'
  actionpack (5.2.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  actionpack (5.2.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  actionpack (5.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (5.2.1) lib/action_controller/metal/rendering.rb:36:in `render'
  actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
  activesupport (5.2.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
  activesupport (5.2.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
  actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
  actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
  actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:45:in `render'
  meta-tags (2.10.0) lib/meta_tags/controller_helper.rb:20:in `render'
  remotipart (1.4.2) lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
  actionpack (5.2.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
  actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
  actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
  actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'
  actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  activesupport (5.2.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
  actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
  actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
  actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
  activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
  actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'
  actionview (5.2.1) lib/action_view/rendering.rb:32:in `process'
   () usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/rack-mini-profiler-ab2d911d2c17/lib/mini_profiler/profiling_methods.rb:104:in `block in profile_method'
  actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'
  actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'
  actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
  actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
  actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
  actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
  actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
  actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
  rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
  rack (2.0.5) lib/rack/method_override.rb:22:in `call'
  rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
  rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
  serviceworker-rails (0.5.5) lib/serviceworker/middleware.rb:32:in `call'
  bullet (5.7.5) lib/bullet/rack.rb:14:in `call'
  remotipart (1.4.2) lib/remotipart/middleware.rb:32:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
  rack (2.0.5) lib/rack/etag.rb:25:in `call'
  rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
  rack-user_agent (0.5.2) lib/rack/user_agent.rb:16:in `call'
  rack (2.0.5) lib/rack/head.rb:12:in `call'
  actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
  rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
  activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
  actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
  better_errors (2.4.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.4.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.4.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
  web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
  web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
  web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
  activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
  activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
  activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
  railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
  sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
  rack (2.0.5) lib/rack/method_override.rb:22:in `call'
  rack (2.0.5) lib/rack/runtime.rb:22:in `call'
  rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
  rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
   () usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/rack-mini-profiler-ab2d911d2c17/lib/mini_profiler/profiler.rb:285:in `call'
  webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
  rack-proxy (0.6.4) lib/rack/proxy.rb:57:in `call'
  railties (5.2.1) lib/rails/engine.rb:524:in `call'
  puma (3.12.0) lib/puma/configuration.rb:225:in `call'
  puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
  puma (3.12.0) lib/puma/server.rb:472:in `process_client'
  puma (3.12.0) lib/puma/server.rb:332:in `block in run'
  puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by yskkin** [comment]
using ransack from master branch fix this issue.
Maybe related to https://github.com/activerecord-hackery/ransack/pull/939

**Comment by yskkin** [comment]
sorry, already reported in  #41

**Comment by nezirz** [comment]
Guys  I am trying latest rails 6.0.0.rc2 and I am using easyautocomplete jquery plugin and gem 'ransack', '~> 2.1', '>= 2.1.1'  I have controller: 

```
class AutocompleteController < ApplicationController
  before_action :authenticate_user!

  def index
    byebug

    if params[:q] && params[:q].include?('@@')
      param = params[:q].remove('@@')

      @profiles = User.ransack(username_cont: param).result.limit(5) 
    
      render json: @profiles.select(:full_name,:username) if @profiles
    end

  end
end 
```

So this works in rails 6.0.0.rc1 but now when I did project upgrade to rails 6.0.0.rc2 I am getting error on line User.ransack...

```
(byebug) User.ransack(username_cont: param).result.limit(5)
*** ArgumentError Exception: wrong number of arguments (given 3, expected 4)
```

Does anybody has any idea whats happening here?

**Comment by nezirz** [comment]
The error is solved by using latest ransack as: 
`gem 'ransack', github: 'activerecord-hackery/ransack'`
